// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA892q2Q9IS87ZR-cVIN2Dq8ZjkNv6BaSE',
    appId: '1:364547647391:web:1abe203d473d26d16abfaa',
    messagingSenderId: '364547647391',
    projectId: 'message-app-52a01',
    authDomain: 'message-app-52a01.firebaseapp.com',
    storageBucket: 'message-app-52a01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABf1vvyJTyJDthdrO5FxVld6jHU7QBS-k',
    appId: '1:364547647391:android:2414ae48ab19d9bc6abfaa',
    messagingSenderId: '364547647391',
    projectId: 'message-app-52a01',
    storageBucket: 'message-app-52a01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMp8gK2X4GXqeNPbX71yPXkFiBo6Q2ylk',
    appId: '1:364547647391:ios:446d20a9edb813d16abfaa',
    messagingSenderId: '364547647391',
    projectId: 'message-app-52a01',
    storageBucket: 'message-app-52a01.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMp8gK2X4GXqeNPbX71yPXkFiBo6Q2ylk',
    appId: '1:364547647391:ios:446d20a9edb813d16abfaa',
    messagingSenderId: '364547647391',
    projectId: 'message-app-52a01',
    storageBucket: 'message-app-52a01.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcyh7dvzXUeqjP817KqxIJJzuNmJrjxg0',
    appId: '1:364547647391:web:0df48913400a57f26abfaa',
    messagingSenderId: '364547647391',
    projectId: 'message-app-52a01',
    authDomain: 'message-app-52a01.firebaseapp.com',
    storageBucket: 'message-app-52a01.appspot.com',
  );

}